default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('PGDATABASE', 'seed_list_development') %>
  username: postgres
  password:
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PGPORT', '32772') %>
  schema_search_path: myapp,sharedapp,public
  min_messages: notice

test:
  <<: *default
  database: seed_list_test
  username: postgres
  password:
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PGPORT', '5432') %>

production:
  <<: *default
  database: seed_list_production
  username: postgres
  password: <%= ENV['SEED_LIST_DATABASE_PASSWORD'] %>
